// examples/chat/App.vue
<script setup lang="ts">
import { computed, ref, shallowRef } from 'vue'
import {
  DirectChatTransport,
  useChat,
  deepseek,
  gemini,
  openai,
  openrouter,
  proxyProvider
} from 'vue-ai-hooks'
import type {
  ChatChunk,
  ChatRequest,
  ImageUrlPart,
  MessageContent,
  MessagePart,
  MessageToolPart,
  Tool,
  ToolCall
} from 'vue-ai-hooks'

type ProviderType =
  'openai' | 'openrouter' | 'gemini' | 'deepseek' | 'proxy' | 'proxy-route' | 'local-tools'

type CheckoutArgs = {
  orderId: string
  plan: string
  amount: number
  currency: string
}

type RenderedMessagePart = {
  key: string
  kind: string
  label: string
  href?: string
  tone: 'reasoning' | 'source' | 'file' | 'data' | 'tool'
}

/**
 * Runtime provider selection for the chat example:
 * - `VITE_CHAT_PROVIDER=openrouter` selects openrouter.
 * - `VITE_CHAT_PROVIDER=gemini` selects Gemini's OpenAI-compatible endpoint.
 * - `VITE_CHAT_PROVIDER=deepseek` selects DeepSeek's OpenAI-compatible endpoint.
 * - `VITE_CHAT_PROVIDER=proxy` selects your app backend proxy.
 * - `VITE_CHAT_PROVIDER=proxy-route` uses default proxy transport at `/api/chat`.
 * - `VITE_CHAT_PROVIDER=local-tools` runs the tool approval demo without keys.
 * - when no provider is selected and no real OpenAI key is present, the demo
 *   starts with local-tools so the first run works without credentials.
 *
 * - openai: created via `openai` and reads `VITE_OPENAI_KEY` + optional
 *   `VITE_OPENAI_BASE_URL`.
 * - openrouter: created via `openrouter` and reads `VITE_OPENROUTER_*` vars.
 * - gemini: created via `gemini` and reads `VITE_GEMINI_*` vars.
 * - deepseek: created via `deepseek` and reads `VITE_DEEPSEEK_*` vars.
 * - proxy: created via `proxyProvider` and reads `VITE_PROXY_*` vars.
 * - local-tools: deterministic DirectChatTransport for testing approval UI locally.
 *
 * Start the demo:
 *   pnpm install
 *   pnpm example:chat
 *   open http://localhost:5174
 */
const configuredProvider =
  import.meta.env.VITE_CHAT_PROVIDER || import.meta.env.VITE_EXAMPLE_PROVIDER
const openAiKey = (import.meta.env.VITE_OPENAI_KEY || '').trim()
const providerName =
  configuredProvider || (openAiKey && openAiKey !== 'sk-...' ? 'openai' : 'local-tools')
const providerType: ProviderType =
  providerName === 'openrouter'
    ? 'openrouter'
    : providerName === 'gemini'
      ? 'gemini'
      : providerName === 'deepseek'
        ? 'deepseek'
        : providerName === 'proxy'
          ? 'proxy'
          : providerName === 'proxy-route'
            ? 'proxy-route'
            : providerName === 'local-tools'
              ? 'local-tools'
              : 'openai'
const proxyCredentials = (import.meta.env.VITE_PROXY_CREDENTIALS || undefined) as
  RequestCredentials | undefined
const proxyBaseURL = (import.meta.env.VITE_PROXY_BASE_URL || '').trim()
const proxyRouteHeaders = import.meta.env.VITE_PROXY_AUTH_TOKEN
  ? { Authorization: `Bearer ${import.meta.env.VITE_PROXY_AUTH_TOKEN}` }
  : undefined
const useProxyRoute = providerType === 'proxy-route'

const checkoutArgs: CheckoutArgs = {
  orderId: 'ord_demo_1042',
  plan: 'Team plan',
  amount: 49,
  currency: 'USD'
}

const chargeCardTool: Tool = {
  type: 'function',
  function: {
    name: 'chargeCard',
    description: 'Charge a saved card after explicit user approval.',
    parameters: {
      type: 'object',
      properties: {
        orderId: { type: 'string' },
        plan: { type: 'string' },
        amount: { type: 'number' },
        currency: { type: 'string' }
      },
      required: ['orderId', 'plan', 'amount', 'currency']
    }
  }
}

function sleep(ms: number) {
  return new Promise((resolve) => window.setTimeout(resolve, ms))
}

function safeJson(value: unknown): Record<string, unknown> {
  if (typeof value !== 'string') return {}
  try {
    const parsed = JSON.parse(value) as unknown
    return parsed && typeof parsed === 'object' ? (parsed as Record<string, unknown>) : {}
  } catch {
    return {}
  }
}

function checkoutFromCall(call: ToolCall): CheckoutArgs {
  return {
    ...checkoutArgs,
    ...safeJson(call.function.arguments)
  }
}

async function* localToolStream(request: ChatRequest): AsyncIterable<ChatChunk> {
  const lastTool = [...request.messages].reverse().find((message) => message.role === 'tool')
  await sleep(80)

  if (lastTool) {
    const result = safeJson(String(lastTool.content))
    const approved = result.approved !== false
    yield {
      dataId: 'charge-result',
      dataType: approved ? 'tool-output-available' : 'tool-output-error',
      data: approved
        ? {
            toolCallId: lastTool.toolCallId || 'call_charge_card',
            toolName: 'chargeCard',
            output: result
          }
        : {
            toolCallId: lastTool.toolCallId || 'call_charge_card',
            toolName: 'chargeCard',
            errorText: 'Checkout was rejected before charging the saved card.'
          }
    }
    const text = !approved
      ? 'Checkout cancelled. No card was charged, and the order is still pending.'
      : `Approved. Receipt ${result.receiptId} is ready for ${result.currency} ${result.amount}.`

    for (const part of text.match(/.{1,24}/g) ?? [text]) {
      await sleep(30)
      yield { content: part }
    }
    yield {
      finishReason: 'stop',
      usage: { promptTokens: 42, completionTokens: 18, totalTokens: 60 }
    }
    return
  }

  yield { content: 'I can prepare checkout, but charging the card needs approval first.' }
  yield {
    dataId: 'use-chat-reference',
    dataType: 'source-url',
    data: {
      url: 'https://github.com/hexinmiao96/vue-ai-hooks/blob/main/docs/reference/use-chat.md',
      title: 'useChat reference'
    }
  }
  yield {
    dataId: 'checkout-policy',
    dataType: 'file',
    data: {
      url: 'https://example.test/checkout-policy.pdf',
      mediaType: 'application/pdf',
      name: 'checkout-policy.pdf'
    }
  }
  await sleep(80)
  yield {
    toolCalls: [
      {
        index: 0,
        id: 'call_charge_card',
        type: 'function',
        function: {
          name: 'chargeCard',
          arguments: JSON.stringify(checkoutArgs)
        }
      }
    ]
  }
  yield { finishReason: 'tool_calls' }
}

const localToolProvider = new DirectChatTransport({
  id: 'local-tools',
  streamProtocol: 'chat-chunk',
  stream: localToolStream
})
/**
 * Build the concrete provider instance used by this example so the compose logic
 * stays explicit and easy to compare in logs and screenshots.
 */
const provider =
  providerType === 'local-tools'
    ? localToolProvider
    : providerType === 'openrouter'
      ? openrouter({
          // Keep app-scoped identity headers configurable for OpenRouter quotas/rules.
          apiKey: import.meta.env.VITE_OPENROUTER_API_KEY || '',
          defaultModel: import.meta.env.VITE_OPENROUTER_DEFAULT_MODEL || 'openai/gpt-4o-mini',
          siteUrl: import.meta.env.VITE_OPENROUTER_SITE_URL,
          appName: import.meta.env.VITE_OPENROUTER_APP_NAME || 'Vue AI Hooks'
        })
      : providerType === 'gemini'
        ? gemini({
            // Gemini uses Google's OpenAI-compatible base by default.
            apiKey: import.meta.env.VITE_GEMINI_API_KEY || '',
            defaultModel: import.meta.env.VITE_GEMINI_DEFAULT_MODEL || 'gemini-3.5-flash',
            baseURL: import.meta.env.VITE_GEMINI_BASE_URL
          })
        : providerType === 'deepseek'
          ? deepseek({
              // DeepSeek uses https://api.deepseek.com by default.
              apiKey: import.meta.env.VITE_DEEPSEEK_API_KEY || '',
              defaultModel: import.meta.env.VITE_DEEPSEEK_DEFAULT_MODEL || 'deepseek-v4-flash',
              baseURL: import.meta.env.VITE_DEEPSEEK_BASE_URL
            })
          : providerType === 'proxy'
            ? proxyProvider({
                // Browser requests go to your app backend; upstream keys stay server-side.
                chatUrl: import.meta.env.VITE_PROXY_CHAT_URL || '/api/ai/chat',
                baseURL: proxyBaseURL,
                credentials: proxyCredentials,
                headers: proxyRouteHeaders
              })
            : openai({
                // Default path is https://api.openai.com/v1 if baseURL is omitted.
                apiKey: import.meta.env.VITE_OPENAI_KEY || '',
                baseURL: import.meta.env.VITE_OPENAI_BASE_URL
              })

const chunkCount = shallowRef(0)
const approvalLog = shallowRef('No approval decision yet.')
const fileInput = shallowRef<HTMLInputElement | null>(null)
const selectedFiles = shallowRef<File[]>([])

// useChat returns both message stream state and imperative controls.
// - messages/input: render + editor binding
// - isLoading: controls request button states
// - handleSubmit/append/stop: form submit, custom send, and cancel lifecycle hooks
// - error: synchronous rendering of transport/composition failures
const {
  messages,
  input,
  isLoading,
  append,
  handleSubmit,
  stop,
  error,
  pendingToolCalls,
  approveToolCall,
  rejectToolCall,
  clearTrace,
  inspect,
  lastRequest,
  lastResponse
} = useChat({
  ...(useProxyRoute
    ? {
        api: '/api/chat',
        ...(proxyBaseURL ? { baseURL: proxyBaseURL } : {}),
        credentials: proxyCredentials,
        ...(proxyRouteHeaders ? { headers: proxyRouteHeaders } : {})
      }
    : {
        provider
      }),
  tools: [chargeCardTool],
  toolHandlers: {
    chargeCard(args) {
      const checkout = { ...checkoutArgs, ...(args as Partial<CheckoutArgs>) }
      approvalLog.value = `Approved ${checkout.orderId} for ${checkout.currency} ${checkout.amount}.`
      return {
        charged: true,
        receiptId: 'rcpt_demo_1042',
        ...checkout
      }
    }
  },
  requiresToolApproval(_args, context) {
    return context.toolCall.function.name === 'chargeCard'
  },
  onChunk: () => {
    chunkCount.value += 1
  },
  onError: (e) => console.error('chat error:', e)
})

const pendingApprovals = computed(() =>
  pendingToolCalls.value
    .filter((call) => call.function.name === 'chargeCard')
    .map((call) => ({
      id: call.id,
      name: call.function.name,
      args: checkoutFromCall(call)
    }))
)

const canStartDemo = computed(() => !isLoading.value && pendingApprovals.value.length === 0)
const canSend = computed(
  () => !isLoading.value && (input.value.trim().length > 0 || selectedFiles.value.length > 0)
)
const inspection = computed(() => inspect())
const copiedStatus = ref('Copy curl')
const inspectionSummary = computed(() => inspection.value.summary)
const inspectionJson = computed(() => JSON.stringify(inspection.value, null, 2))
const inspectionTimeline = computed(() => inspection.value.timeline)
const inspectionRetries = computed(() => inspection.value.retries)
const lastRequestJson = computed(() => JSON.stringify(lastRequest.value, null, 2))
const lastResponseJson = computed(() => JSON.stringify(lastResponse.value, null, 2))

async function copyInspectionCurl() {
  if (!inspection.value.curl) return
  await navigator.clipboard.writeText(inspection.value.curl)
  copiedStatus.value = 'Copied'
  window.setTimeout(() => {
    copiedStatus.value = 'Copy curl'
  }, 1200)
}
const traceRows = computed(() => [
  {
    label: 'Provider',
    value:
      inspection.value.providerId ??
      (providerType === 'proxy-route' ? 'proxy-transport' : provider.id)
  },
  {
    label: 'Attempt',
    value: inspection.value.request ? String(inspection.value.request.attempt) : 'idle'
  },
  { label: 'Kind', value: inspection.value.request?.kind ?? 'chat' },
  { label: 'Status', value: inspection.value.status },
  {
    label: 'Stream',
    value: inspection.value.response?.hasStream ? 'stream open' : 'no stream'
  },
  { label: 'Timeline', value: String(inspection.value.timeline.length) },
  { label: 'Retries', value: String(inspection.value.retries.length) }
])
const renderedMessages = computed(() =>
  messages.value.map((message) => ({
    id: message.id,
    role: message.role,
    text: messageText(message.content),
    images: messageImages(message.content),
    parts: visibleMessageParts(message.parts),
    toolCalls: message.toolCalls ?? []
  }))
)

function handleFileChange(event: Event) {
  const target = event.target as HTMLInputElement
  selectedFiles.value = Array.from(target.files ?? [])
}

function clearSelectedFiles() {
  selectedFiles.value = []
  if (fileInput.value) fileInput.value.value = ''
}

function messageText(content: MessageContent): string {
  if (typeof content === 'string') return content
  return content
    .filter((part) => part.type === 'text')
    .map((part) => part.text)
    .join('\n\n')
}

function messageImages(content: MessageContent): ImageUrlPart[] {
  if (typeof content === 'string') return []
  return content.filter((part): part is ImageUrlPart => part.type === 'image_url')
}

function isToolPart(part: MessagePart): part is MessageToolPart {
  return part.type.startsWith('tool-')
}

function formatPreviewData(value: unknown): string {
  if (typeof value === 'string') return value
  const serialized = JSON.stringify(value)
  if (!serialized) return 'data'
  return serialized.length > 90 ? `${serialized.slice(0, 87)}...` : serialized
}

function visibleMessageParts(parts: MessagePart[] | undefined): RenderedMessagePart[] {
  return (parts ?? [])
    .filter((part) => part.type !== 'text')
    .map((part, index) => {
      if (part.type === 'reasoning') {
        return {
          key: part.id ?? `reasoning-${index}`,
          kind: 'reasoning',
          label: part.text,
          tone: 'reasoning'
        }
      }
      if (part.type === 'source') {
        return {
          key: part.id ?? `source-${index}`,
          kind: part.sourceType === 'document' ? 'source document' : 'source url',
          label: part.title ?? part.url ?? 'source',
          href: part.url,
          tone: 'source'
        }
      }
      if (part.type === 'file') {
        return {
          key: part.id ?? `file-${index}`,
          kind: 'file',
          label: part.name ?? part.mediaType ?? part.url,
          href: part.url,
          tone: 'file'
        }
      }
      if (isToolPart(part)) {
        return {
          key: part.toolCallId,
          kind: part.type,
          label: `${part.toolName}: ${part.state}`,
          tone: 'tool'
        }
      }
      return {
        key: part.id ?? `${part.type}-${index}`,
        kind: part.type,
        label: formatPreviewData(part.data),
        tone: 'data'
      }
    })
}

/**
 * Send current input as a new user message when valid and idle.
 *
 * This guard prevents accidental empty submits and duplicate in-flight requests.
 */
async function send(event?: { preventDefault?: () => void }) {
  event?.preventDefault?.()
  // Ignore empty input or duplicate sends while a request is already running.
  if (!canSend.value) return
  chunkCount.value = 0
  await handleSubmit(undefined, {
    attachments: selectedFiles.value.length ? selectedFiles.value : undefined
  })
  clearSelectedFiles()
}

async function startApprovalDemo() {
  if (!canStartDemo.value) return
  chunkCount.value = 0
  approvalLog.value = 'Waiting for checkout approval.'
  input.value = ''
  clearSelectedFiles()
  await append('Run the checkout approval demo.')
}

async function approveCheckout(callId: string) {
  await approveToolCall(callId)
}

async function rejectCheckout(callId: string) {
  approvalLog.value = 'Rejected checkout request.'
  await rejectToolCall(callId, 'User denied checkout')
}
</script>

<template>
  <main class="chat">
    <h1>vue-ai-hooks · useChat</h1>
    <p v-if="error" class="error">
      {{ error.message }}
    </p>
    <p class="provider-badge">Provider: {{ providerType }} · chunks: {{ chunkCount }}</p>
    <section class="inspect-panel" aria-label="request inspection">
      <h2>Inspection</h2>
      <p class="inspect-summary">{{ inspectionSummary }}</p>
      <div class="inspect-actions">
        <button type="button" :disabled="!inspection.curl" @click="copyInspectionCurl">
          {{ copiedStatus }}
        </button>
        <button type="button" @click="clearTrace">Clear trace</button>
      </div>
      <dl class="trace-panel" aria-label="inspection snapshot">
        <div v-for="row in traceRows" :key="row.label">
          <dt>{{ row.label }}</dt>
          <dd>{{ row.value }}</dd>
        </div>
      </dl>
      <details>
        <summary>Timeline ({{ inspectionTimeline.length }})</summary>
        <ul class="trace-list">
          <li
            v-for="event in inspectionTimeline"
            :key="`${event.kind}-${event.timestamp}-${event.label}`"
          >
            {{ event.kind }}{{ event.attempt ? ` #${event.attempt}` : '' }} —
            {{ event.label || event.message || 'event' }}
          </li>
        </ul>
      </details>
      <details>
        <summary>Retries ({{ inspectionRetries.length }})</summary>
        <ul class="trace-list">
          <li v-for="retry in inspectionRetries" :key="`r-${retry.attempt}-${retry.timestamp}`">
            #{{ retry.attempt }}: {{ retry.error.category }} — {{ retry.error.message }}
          </li>
        </ul>
      </details>
      <details>
        <summary>Provider trace</summary>
        <pre class="trace-code">{{ JSON.stringify(inspection.providerTrace, null, 2) }}</pre>
      </details>
      <details>
        <summary>Raw request/response</summary>
        <pre class="trace-code">lastRequest: {{ lastRequestJson }}</pre>
        <pre class="trace-code">lastResponse: {{ lastResponseJson }}</pre>
      </details>
      <details>
        <summary>Full snapshot</summary>
        <pre class="trace-code">{{ inspectionJson }}</pre>
      </details>
      <pre v-if="inspection.curl" class="trace-code">curl: {{ inspection.curl }}</pre>
    </section>
    <button class="demo-trigger" :disabled="!canStartDemo" @click="startApprovalDemo">
      Run approval demo
    </button>

    <section class="messages">
      <article v-for="m in renderedMessages" :key="m.id" :class="['message', `role-${m.role}`]">
        <header>{{ m.role }}</header>
        <p v-if="m.text" class="message-text">{{ m.text }}</p>
        <div v-if="m.images.length" class="message-images">
          <img
            v-for="image in m.images"
            :key="image.image_url.url"
            :src="image.image_url.url"
            alt="Attached image preview"
          />
        </div>
        <ul v-if="m.parts.length" class="message-parts" aria-label="structured message parts">
          <li v-for="part in m.parts" :key="part.key" :class="`is-${part.tone}`">
            <span>{{ part.kind }}</span>
            <a v-if="part.href" :href="part.href" target="_blank" rel="noreferrer">
              {{ part.label }}
            </a>
            <strong v-else>{{ part.label }}</strong>
          </li>
        </ul>
        <ul v-if="m.toolCalls.length" class="tool-call-list" aria-label="tool calls">
          <li v-for="call in m.toolCalls" :key="call.id">requested {{ call.function.name }}</li>
        </ul>
      </article>
    </section>

    <section v-if="pendingApprovals.length" class="approval-panel" aria-live="polite">
      <article v-for="approval in pendingApprovals" :key="approval.id" class="approval-request">
        <div class="approval-heading">
          <span>Approval required</span>
          <strong>{{ approval.name }}</strong>
        </div>
        <dl>
          <div>
            <dt>Order</dt>
            <dd>{{ approval.args.orderId }}</dd>
          </div>
          <div>
            <dt>Plan</dt>
            <dd>{{ approval.args.plan }}</dd>
          </div>
          <div>
            <dt>Amount</dt>
            <dd>{{ approval.args.currency }} {{ approval.args.amount }}</dd>
          </div>
        </dl>
        <div class="approval-actions">
          <button class="approve" :disabled="isLoading" @click="approveCheckout(approval.id)">
            Approve
          </button>
          <button class="reject" :disabled="isLoading" @click="rejectCheckout(approval.id)">
            Reject
          </button>
        </div>
      </article>
    </section>

    <p class="approval-log">{{ approvalLog }}</p>

    <form class="composer" @submit="send">
      <textarea
        v-model="input"
        rows="3"
        placeholder="Say something..."
        @keydown.enter.exact.prevent="send()"
      />
      <label class="file-picker">
        <span>Attach image/text</span>
        <input
          ref="fileInput"
          type="file"
          accept="image/*,text/*"
          multiple
          @change="handleFileChange"
        />
      </label>
      <ul v-if="selectedFiles.length" class="selected-files" aria-label="selected files">
        <li v-for="file in selectedFiles" :key="`${file.name}-${file.size}`">
          {{ file.name || file.type || 'attachment' }}
        </li>
      </ul>
      <div class="actions">
        <button :disabled="!canSend">Send</button>
        <button type="button" :disabled="!isLoading" @click="stop">Stop</button>
      </div>
    </form>
  </main>
</template>

<style scoped>
.chat {
  max-width: 760px;
  margin: 32px auto;
  font-family: system-ui, sans-serif;
  color: #172033;
}
h1 {
  font-size: 18px;
}
.messages {
  display: flex;
  flex-direction: column;
  gap: 12px;
  margin: 16px 0;
}
.message {
  padding: 10px 12px;
  border-radius: 8px;
  border: 1px solid #e2e8f0;
}
.message header {
  font-size: 12px;
  color: #666;
  margin-bottom: 4px;
}
.message-text {
  white-space: pre-wrap;
}
.message-images {
  display: grid;
  gap: 8px;
  margin-top: 8px;
}
.message-images img {
  max-width: min(100%, 320px);
  border: 1px solid #cbd5e1;
  border-radius: 8px;
}
.role-user {
  background: #f0f7ff;
}
.role-assistant {
  background: #f7f7f7;
}
.role-tool {
  background: #f2fbf6;
}
.trace-panel {
  display: grid;
  grid-template-columns: repeat(4, minmax(0, 1fr));
  gap: 8px;
  margin: 12px 0;
}
.trace-panel div {
  min-width: 0;
  padding: 8px 10px;
  border: 1px solid #cbd5e1;
  border-radius: 8px;
  background: #ffffff;
}
.trace-panel dt {
  margin-bottom: 3px;
  color: #64748b;
  font-size: 11px;
  font-weight: 700;
  text-transform: uppercase;
}
.trace-panel dd {
  margin: 0;
  overflow-wrap: anywhere;
  color: #172033;
  font-size: 13px;
  font-weight: 700;
}
.tool-call-list {
  display: flex;
  flex-wrap: wrap;
  gap: 6px;
  padding: 0;
  margin: 8px 0 0;
  list-style: none;
}
.tool-call-list li {
  padding: 4px 8px;
  border: 1px solid #f59e0b;
  border-radius: 999px;
  color: #92400e;
  background: #fffbeb;
  font-size: 12px;
}
.message-parts {
  display: grid;
  gap: 6px;
  padding: 0;
  margin: 10px 0 0;
  list-style: none;
}
.message-parts li {
  display: grid;
  grid-template-columns: minmax(96px, auto) minmax(0, 1fr);
  gap: 8px;
  align-items: center;
  padding: 7px 9px;
  border: 1px solid #cbd5e1;
  border-radius: 8px;
  background: #ffffff;
  font-size: 12px;
}
.message-parts span {
  color: #64748b;
  font-weight: 700;
}
.message-parts strong,
.message-parts a {
  min-width: 0;
  overflow-wrap: anywhere;
  color: #172033;
  font-weight: 700;
  text-decoration: none;
}
.message-parts a:hover {
  color: #1d4ed8;
  text-decoration: underline;
}
.message-parts .is-source {
  border-color: #93c5fd;
  background: #eff6ff;
}
.message-parts .is-file {
  border-color: #c4b5fd;
  background: #f5f3ff;
}
.message-parts .is-tool {
  border-color: #fed7aa;
  background: #fff7ed;
}
.message-parts .is-reasoning,
.message-parts .is-data {
  border-color: #bbf7d0;
  background: #f0fdf4;
}
.approval-panel {
  display: grid;
  gap: 12px;
  margin: 16px 0;
}
.approval-request {
  padding: 14px;
  border: 1px solid #f97316;
  border-radius: 8px;
  background: #fff7ed;
}
.approval-heading {
  display: flex;
  align-items: baseline;
  justify-content: space-between;
  gap: 12px;
  margin-bottom: 12px;
}
.approval-heading span {
  color: #9a3412;
  font-size: 12px;
  font-weight: 700;
  text-transform: uppercase;
}
.approval-heading strong {
  color: #172033;
}
.approval-request dl {
  display: grid;
  grid-template-columns: repeat(3, minmax(0, 1fr));
  gap: 10px;
  margin: 0 0 12px;
}
.approval-request dt {
  color: #64748b;
  font-size: 12px;
}
.approval-request dd {
  margin: 3px 0 0;
  font-weight: 700;
}
.approval-actions {
  display: flex;
  gap: 8px;
}
.approval-log {
  min-height: 18px;
  margin: 0 0 12px;
  color: #475569;
  font-size: 13px;
}
.composer {
  display: flex;
  flex-direction: column;
  gap: 8px;
}
textarea {
  width: 100%;
  padding: 8px;
  font: inherit;
}
.file-picker {
  display: inline-flex;
  align-items: center;
  gap: 8px;
  color: #334155;
  font-size: 13px;
}
.file-picker input {
  max-width: 100%;
}
.selected-files {
  display: flex;
  flex-wrap: wrap;
  gap: 6px;
  padding: 0;
  margin: 0;
  list-style: none;
}
.selected-files li {
  padding: 4px 8px;
  border: 1px solid #cbd5e1;
  border-radius: 999px;
  background: #f8fafc;
  color: #334155;
  font-size: 12px;
}
.actions {
  display: flex;
  gap: 8px;
}
button {
  padding: 8px 16px;
  border: 1px solid #cbd5e1;
  border-radius: 6px;
  background: #ffffff;
  color: #172033;
  cursor: pointer;
}
button:disabled {
  cursor: not-allowed;
  opacity: 0.55;
}
.demo-trigger {
  margin-bottom: 4px;
  border-color: #2563eb;
  color: #1d4ed8;
}
.approve {
  border-color: #16a34a;
  background: #16a34a;
  color: #ffffff;
}
.reject {
  border-color: #dc2626;
  color: #b91c1c;
}
.error {
  color: #b00020;
}
.inspect-panel {
  margin: 12px 0;
  border: 1px solid #e2e8f0;
  border-radius: 10px;
  padding: 10px 12px;
  background: #f8fafc;
}
.inspect-summary {
  margin: 0 0 8px;
  color: #334155;
  font-size: 12px;
}
.inspect-actions {
  display: flex;
  gap: 8px;
  margin-bottom: 12px;
}
.trace-list {
  margin: 0 0 12px;
  padding-left: 20px;
}
.trace-list li {
  margin-bottom: 6px;
  line-height: 1.4;
}
.trace-code {
  background: #0f172a;
  border-radius: 6px;
  color: #d1fae5;
  display: block;
  margin: 0 0 12px;
  overflow: auto;
  padding: 8px;
  white-space: pre-wrap;
  word-break: break-all;
}
.provider-badge {
  margin: 0 0 12px;
  font-size: 12px;
  color: #334155;
}
@media (max-width: 640px) {
  .chat {
    margin: 20px 12px;
  }
  .approval-request dl {
    grid-template-columns: 1fr;
  }
}
</style>

// examples/react-chat/App.tsx
import { DirectChatTransport, inspectRequestTrace } from 'vue-ai-hooks'
import { useCallback, useMemo, useState } from 'react'
import {
  createPromptSuggestionRecipes,
  useChat,
  usePromptSuggestions,
  type ChatChunk,
  type ChatRequest,
  type Message
} from 'vue-ai-hooks/react'

const samplePrompts = [
  'Show me the minimum React integration path.',
  'How should I keep provider keys out of the browser?',
  'What should I inspect when a stream fails?'
]

const starterPrompts = createPromptSuggestionRecipes({
  surfaces: ['chat', 'backend'],
  metadata: { surface: 'react-chat' }
})

function sleep(ms: number) {
  return new Promise((resolve) => window.setTimeout(resolve, ms))
}

function messageText(message: Message): string {
  if (typeof message.content === 'string') return message.content
  return message.content
    .filter((part) => part.type === 'text')
    .map((part) => part.text)
    .join('')
}

function requestText(request: ChatRequest): string {
  const lastUser = [...request.messages].reverse().find((message) => message.role === 'user')
  if (!lastUser) return 'Hello from React.'
  if (typeof lastUser.content === 'string') return lastUser.content
  return lastUser.content
    .filter((part) => part.type === 'text')
    .map((part) => part.text)
    .join('')
}

const useProxyRoute = import.meta.env.VITE_CHAT_PROVIDER === 'proxy-route'
const proxyCredentials = (import.meta.env.VITE_PROXY_CREDENTIALS || undefined) as
  RequestCredentials | undefined
const proxyBaseURL = (import.meta.env.VITE_PROXY_BASE_URL || '').trim()
const proxyRouteHeaders = import.meta.env.VITE_PROXY_AUTH_TOKEN
  ? { Authorization: `Bearer ${import.meta.env.VITE_PROXY_AUTH_TOKEN}` }
  : undefined

async function* localReactStream(request: ChatRequest): AsyncIterable<ChatChunk> {
  const prompt = requestText(request)
  const reply = [
    `Received "${prompt}". `,
    'This React demo uses vue-ai-hooks/react for state and DirectChatTransport for a no-key stream. ',
    'Swap the provider for proxyProvider or your own /api/chat route when moving to production.'
  ]

  for (const chunk of reply) {
    await sleep(80)
    yield { content: chunk }
  }

  yield {
    dataId: 'react-demo-trace',
    dataType: 'demo-trace',
    data: {
      provider: 'react-local',
      messageCount: request.messages.length,
      streamProtocol: request.streamProtocol ?? 'chat-chunk'
    }
  }
  yield {
    finishReason: 'stop',
    usage: { promptTokens: 24, completionTokens: 36, totalTokens: 60 }
  }
}

const provider = new DirectChatTransport({
  id: 'react-local',
  streamProtocol: 'chat-chunk',
  stream: localReactStream
})

export default function App() {
  const {
    messages,
    input,
    setInput,
    handleInputChange,
    handleSubmit,
    isLoading,
    status: chatStatus,
    stop,
    clear,
    usage,
    streamData,
    lastRequest,
    lastResponse,
    clearTrace,
    error: chatError
  } = useChat({
    ...(useProxyRoute
      ? {
          api: '/api/chat',
          ...(proxyBaseURL ? { baseURL: proxyBaseURL } : {}),
          credentials: proxyCredentials,
          ...(proxyRouteHeaders ? { headers: proxyRouteHeaders } : {})
        }
      : {
          provider
        }),
    initialInput: samplePrompts[0],
    defaultRequest: {
      streamProtocol: 'ui-message',
      metadata: { demo: 'react-chat' }
    }
  })
  const { visibleSuggestions } = usePromptSuggestions({
    suggestions: [
      ...samplePrompts.map((prompt, index) => ({
        id: `react-chat-prompt-${index + 1}`,
        prompt
      })),
      ...starterPrompts
    ],
    input,
    messages,
    max: 6
  })
  const [copiedStatus, setCopiedStatus] = useState('Copy curl')
  const inspection = useMemo(
    () =>
      inspectRequestTrace({
        status: chatStatus,
        lastRequest,
        lastResponse,
        error: chatError,
        curl: true
      }),
    [chatStatus, lastRequest, lastResponse, chatError]
  )
  const inspectionSummary = useMemo(() => JSON.stringify(inspection, null, 2), [inspection])
  const copyInspectionCurl = useCallback(() => {
    if (!inspection.curl) return
    void navigator.clipboard.writeText(inspection.curl)
    setCopiedStatus('Copied')
    window.setTimeout(() => {
      setCopiedStatus('Copy curl')
    }, 1200)
  }, [inspection.curl])

  const canSubmit = input.trim().length > 0 && !isLoading
  const providerId = inspection.providerId ?? (useProxyRoute ? 'proxy-transport' : provider.id)
  const inspectionRows = [
    { label: 'Provider', value: providerId },
    {
      label: 'Request',
      value: inspection.request
        ? `${inspection.request.kind} #${inspection.request.attempt}`
        : 'none'
    },
    { label: 'Status', value: inspection.status },
    {
      label: 'Stream',
      value: inspection.response?.hasStream ? 'open' : 'no stream'
    },
    {
      label: 'Timeline',
      value: String(inspection.timeline.length)
    },
    {
      label: 'Retries',
      value: String(inspection.retries.length)
    },
    { label: 'Attempt', value: String(inspection.attempt ?? 'none') }
  ]

  return (
    <main className="app-shell">
      <section className="conversation-panel" aria-label="React chat demo">
        <header className="toolbar">
          <div>
            <p className="eyebrow">vue-ai-hooks/react</p>
            <h1>React chat quickstart</h1>
          </div>
          <div className="status-strip" aria-label="Request status">
            <span data-status={chatStatus}>{chatStatus}</span>
            <span>{messages.length} messages</span>
          </div>
        </header>

        <div className="sample-grid" aria-label="Prompt suggestions">
          {visibleSuggestions.map((suggestion) => (
            <button
              className="sample-button"
              disabled={isLoading}
              key={suggestion.id}
              onClick={() => {
                setInput(suggestion.prompt)
              }}
              type="button"
            >
              {suggestion.prompt}
            </button>
          ))}
        </div>

        <div className="message-list" aria-live="polite">
          {messages.length === 0 ? (
            <p className="empty-state">Send a prompt to see the local React stream.</p>
          ) : (
            messages.map((message) => (
              <article className="message-row" data-role={message.role} key={message.id}>
                <strong>{message.role}</strong>
                <p>{messageText(message)}</p>
              </article>
            ))
          )}
        </div>

        <form className="composer" onSubmit={handleSubmit}>
          <textarea
            aria-label="Prompt"
            onChange={handleInputChange}
            placeholder="Ask about the React integration..."
            rows={3}
            value={input}
          />
          <div className="composer-actions">
            <button disabled={!canSubmit} type="submit">
              Send
            </button>
            <button disabled={!isLoading} onClick={stop} type="button">
              Stop
            </button>
            <button disabled={isLoading && messages.length === 0} onClick={clear} type="button">
              Clear
            </button>
          </div>
        </form>

        {chatError ? <p className="error-text">{chatError.message}</p> : null}
      </section>

      <aside className="inspect-panel" aria-label="Request inspection">
        <h2>Inspection</h2>
        <p className="inspect-summary">{inspection.summary}</p>
        <div className="inspect-actions">
          <button type="button" disabled={!inspection.curl} onClick={copyInspectionCurl}>
            {copiedStatus}
          </button>
          <button type="button" onClick={clearTrace}>
            Clear trace
          </button>
        </div>
        <dl>
          {inspectionRows.map((row) => (
            <div key={row.label}>
              <dt>{row.label}</dt>
              <dd>{row.value}</dd>
            </div>
          ))}
          <div>
            <dt>Usage</dt>
            <dd>{usage ? `${usage.totalTokens} tokens` : 'pending'}</dd>
          </div>
          <div>
            <dt>Data parts</dt>
            <dd>{streamData.length}</dd>
          </div>
        </dl>
        <details>
          <summary>Timeline ({inspection.timeline.length})</summary>
          <ul className="trace-list">
            {inspection.timeline.map((event) => (
              <li
                key={`${event.kind}-${event.timestamp}-${event.message ?? event.label ?? event.category ?? event.attempt}`}
              >
                {event.kind}
                {event.attempt ? ` #${event.attempt}` : ''}
                {` — ${event.label ?? event.message ?? 'event'}`}
              </li>
            ))}
          </ul>
        </details>
        <details>
          <summary>Retries ({inspection.retries.length})</summary>
          <ul className="trace-list">
            {inspection.retries.map((retry) => (
              <li key={`r-${retry.attempt}-${retry.timestamp}`}>
                #{retry.attempt}: {retry.error.category} — {retry.error.message}
              </li>
            ))}
          </ul>
        </details>
        <details>
          <summary>Provider trace</summary>
          <pre className="trace-code">{JSON.stringify(inspection.providerTrace, null, 2)}</pre>
        </details>

        <pre className="trace-code">{inspectionSummary}</pre>
      </aside>
    </main>
  )
}
