// examples/react-completion/App.tsx
import { useCallback, useMemo, useState } from 'react'
import {
  inspectRequestTrace,
  proxyProvider,
  type ChatProvider,
  type CompletionRequest
} from 'vue-ai-hooks'
import { useCompletion } from 'vue-ai-hooks/react'

const samplePrompts = [
  'Write a short changelog entry for a production release.',
  'Explain this repo in one practical line.',
  'Summarize a risk checklist for shipping LLM features.'
]

function sleep(ms: number) {
  return new Promise((resolve) => window.setTimeout(resolve, ms))
}

function localCompletionText(request: CompletionRequest): string {
  return request.prompt?.trim() || 'Generate a production-grade completion.'
}

async function* localCompletionStream(request: CompletionRequest): AsyncIterable<string> {
  const prompt = localCompletionText(request)
  const reply = [
    `Received "${prompt}". `,
    'This is a deterministic React completion demo. ',
    'Swap in proxyProvider when you are ready to use /api/completion.'
  ]

  for (const chunk of reply) {
    await sleep(90)
    yield chunk
  }
}

const localCompletionProvider: ChatProvider = {
  id: 'react-local-completion',
  async completion(request) {
    return localCompletionStream(request)
  },
  async chat() {
    return (async function* () {
      yield { content: 'This local completion provider does not expose chat.' }
    })()
  },
  async embedding() {
    return {
      embeddings: [],
      model: 'react-local-completion',
      usage: { promptTokens: 0, totalTokens: 0 }
    }
  }
}

const useProxy = import.meta.env.VITE_EXAMPLE_PROVIDER === 'proxy'
const proxyCredentials = (import.meta.env.VITE_PROXY_CREDENTIALS || undefined) as
  RequestCredentials | undefined
const proxyBaseURL = (import.meta.env.VITE_PROXY_BASE_URL || '').trim()
const provider = useProxy
  ? proxyProvider({
      completionUrl: import.meta.env.VITE_PROXY_COMPLETION_URL || '/api/completion',
      baseURL: proxyBaseURL,
      credentials: proxyCredentials,
      headers: import.meta.env.VITE_PROXY_AUTH_TOKEN
        ? { Authorization: `Bearer ${import.meta.env.VITE_PROXY_AUTH_TOKEN}` }
        : undefined
    })
  : localCompletionProvider

export default function App() {
  const [copiedStatus, setCopiedStatus] = useState('Copy curl')
  const {
    completion,
    input,
    status,
    isLoading,
    error,
    clear,
    clearTrace,
    complete,
    handleSubmit,
    handleInputChange,
    stop,
    lastRequest,
    lastResponse
  } = useCompletion({
    provider,
    initialInput: samplePrompts[0],
    defaultRequest: {
      model: import.meta.env.VITE_EXAMPLE_COMPLETION_MODEL || 'gpt-4.1-mini',
      streamProtocol: 'text',
      temperature: 0.25
    }
  })

  const inspection = useMemo(
    () =>
      inspectRequestTrace({
        status,
        error,
        lastRequest,
        lastResponse,
        curl: true
      }),
    [status, error, lastRequest, lastResponse]
  )

  const inspectionSummary = useMemo(() => JSON.stringify(inspection, null, 2), [inspection])
  const canSubmit = input.trim().length > 0 && !isLoading
  const copyCurl = useCallback(() => {
    if (!inspection.curl) return
    void navigator.clipboard.writeText(inspection.curl)
    setCopiedStatus('Copied')
    window.setTimeout(() => {
      setCopiedStatus('Copy curl')
    }, 1200)
  }, [inspection.curl])

  return (
    <main className="react-demo-shell">
      <header className="demo-header" aria-label="React completion quickstart">
        <p className="eyebrow">vue-ai-hooks/react</p>
        <h1>React completion quickstart</h1>
        <p className="status-row">
          <span data-status={status}>{status}</span>
          <span>provider: {provider.id}</span>
        </p>
      </header>

      <section className="card">
        <h2>Prompt</h2>
        <div className="sample-grid">
          {samplePrompts.map((prompt) => (
            <button
              className="sample-button"
              disabled={isLoading}
              key={prompt}
              onClick={() => {
                void complete(prompt)
              }}
              type="button"
            >
              {prompt}
            </button>
          ))}
        </div>
        <textarea value={input} onChange={handleInputChange} rows={3} />
        <div className="composer-actions">
          <button disabled={!canSubmit} onClick={handleSubmit} type="button">
            Complete
          </button>
          <button disabled={!isLoading} onClick={stop} type="button">
            Stop
          </button>
          <button disabled={!completion && !error} onClick={clear} type="button">
            Clear
          </button>
        </div>
        {error ? <p className="error-text">{error.message}</p> : null}
      </section>

      <section className="card">
        <h2>Completion</h2>
        <pre className="pre-output">{completion || 'No completion yet.'}</pre>
      </section>

      <section className="card">
        <h2>Inspection</h2>
        <p className="inspect-summary">{inspection.summary}</p>
        <div className="inspect-actions">
          <button type="button" onClick={copyCurl} disabled={!inspection.curl}>
            {copiedStatus}
          </button>
          <button type="button" onClick={clearTrace}>
            Clear trace
          </button>
        </div>
        <pre className="pre-output">{inspectionSummary}</pre>
      </section>
    </main>
  )
}

// examples/object/App.vue
<script setup lang="ts">
import { computed } from 'vue'
import { useObject, gemini, openai, openrouter, proxyProvider } from 'vue-ai-hooks'
import type { ChatChunk, ChatProvider, ChatRequest, MessageContent } from 'vue-ai-hooks'

type ProviderType = 'openai' | 'openrouter' | 'gemini' | 'proxy' | 'local-object'

type Ticket = {
  title: string
  priority: 'low' | 'high'
}

const schema = {
  type: 'object',
  properties: {
    title: { type: 'string' },
    priority: { type: 'string', enum: ['low', 'high'] }
  },
  required: ['title', 'priority'],
  additionalProperties: false
}

const configuredProvider =
  import.meta.env.VITE_EXAMPLE_PROVIDER || import.meta.env.VITE_CHAT_PROVIDER
const openAiKey = (import.meta.env.VITE_OPENAI_KEY || '').trim()
const providerName =
  configuredProvider || (openAiKey && openAiKey !== 'sk-...' ? 'openai' : 'local-object')
const providerType: ProviderType =
  providerName === 'openrouter'
    ? 'openrouter'
    : providerName === 'gemini'
      ? 'gemini'
      : providerName === 'proxy'
        ? 'proxy'
        : providerName === 'local-object'
          ? 'local-object'
          : 'openai'
const proxyCredentials = (import.meta.env.VITE_PROXY_CREDENTIALS || undefined) as
  RequestCredentials | undefined

function sleep(ms: number) {
  return new Promise((resolve) => window.setTimeout(resolve, ms))
}

function contentText(content: MessageContent) {
  if (typeof content === 'string') return content
  return content
    .map((part) => (part.type === 'text' ? part.text : ''))
    .filter(Boolean)
    .join(' ')
}

function latestUserPrompt(request: ChatRequest) {
  const message = [...request.messages].reverse().find((item) => item.role === 'user')
  return message ? contentText(message.content) : ''
}

function ticketFromPrompt(prompt: string): Ticket {
  const normalized = prompt.replace(/\s+/g, ' ').trim() || 'Customer needs help'
  return {
    title: normalized.length > 52 ? `${normalized.slice(0, 49)}...` : normalized,
    priority: /urgent|blocked|down|无法|紧急|阻塞/i.test(normalized) ? 'high' : 'low'
  }
}

async function* localObjectStream(request: ChatRequest): AsyncIterable<ChatChunk> {
  const text = JSON.stringify(ticketFromPrompt(latestUserPrompt(request)))
  const midpoint = Math.ceil(text.length / 2)
  await sleep(100)
  yield { content: text.slice(0, midpoint) }
  await sleep(100)
  yield { content: text.slice(midpoint) }
  yield {
    finishReason: 'stop',
    usage: { promptTokens: 12, completionTokens: 18, totalTokens: 30 }
  }
}

const localObjectProvider: ChatProvider = {
  id: 'local-object',
  async chat(request) {
    return localObjectStream(request)
  },
  async completion() {
    return (async function* () {
      yield ''
    })()
  },
  async embedding() {
    return { embeddings: [], model: 'local-object', usage: { promptTokens: 0, totalTokens: 0 } }
  }
}

const provider =
  providerType === 'local-object'
    ? localObjectProvider
    : providerType === 'openrouter'
      ? openrouter({
          apiKey: import.meta.env.VITE_OPENROUTER_API_KEY || '',
          defaultModel: import.meta.env.VITE_OPENROUTER_DEFAULT_MODEL || 'openai/gpt-4o-mini',
          siteUrl: import.meta.env.VITE_OPENROUTER_SITE_URL,
          appName: import.meta.env.VITE_OPENROUTER_APP_NAME || 'Vue AI Hooks'
        })
      : providerType === 'gemini'
        ? gemini({
            apiKey: import.meta.env.VITE_GEMINI_API_KEY || '',
            defaultModel: import.meta.env.VITE_GEMINI_DEFAULT_MODEL || 'gemini-3.5-flash',
            baseURL: import.meta.env.VITE_GEMINI_BASE_URL
          })
        : providerType === 'proxy'
          ? proxyProvider({
              chatUrl:
                import.meta.env.VITE_PROXY_OBJECT_URL ||
                import.meta.env.VITE_PROXY_CHAT_URL ||
                '/api/ai/object',
              baseURL: import.meta.env.VITE_PROXY_BASE_URL,
              credentials: proxyCredentials,
              headers: import.meta.env.VITE_PROXY_AUTH_TOKEN
                ? { Authorization: `Bearer ${import.meta.env.VITE_PROXY_AUTH_TOKEN}` }
                : undefined
            })
          : openai({
              apiKey: import.meta.env.VITE_OPENAI_KEY || '',
              baseURL: import.meta.env.VITE_OPENAI_BASE_URL
            })

const {
  object,
  partialObject,
  text,
  input,
  status,
  isLoading,
  submit,
  stop,
  clear,
  error,
  inspect,
  clearTrace
} = useObject<Ticket>({
  provider,
  schema,
  schemaName: 'support_ticket',
  initialValue: { priority: 'low' }
})

input.value = 'Urgent: customer cannot reset password and account access is blocked.'

const visibleObject = computed(() => object.value ?? partialObject.value)
const inspection = computed(() => inspect())
const inspectionJson = computed(() => JSON.stringify(inspection.value, null, 2))
const copied = computed(() => (inspection.value.curl ? 'Copy curl' : 'No curl'))

async function run() {
  await submit(input.value)
}

function formatText(value: unknown) {
  try {
    return JSON.stringify(value, null, 2)
  } catch {
    return String(value)
  }
}

async function copyCurl() {
  if (!inspection.value.curl) return
  await navigator.clipboard.writeText(inspection.value.curl)
}
</script>

<template>
  <main class="object-demo">
    <header class="header">
      <h1 class="title">vue-ai-hooks · useObject</h1>
      <p class="provider-badge">Provider: {{ providerType }}</p>
    </header>

    <p v-if="error" class="error">
      {{ error.message }}
    </p>

    <label class="field">
      Prompt
      <textarea v-model="input" rows="4" class="textarea" />
    </label>

    <div class="actions">
      <button class="button" :disabled="isLoading" @click="run">Extract object</button>
      <button class="button" :disabled="!isLoading" @click="stop">Stop</button>
      <button class="button" :disabled="isLoading" @click="clear">Clear</button>
    </div>

    <section class="panel">
      <h2 class="section-title">Schema</h2>
      <ul class="schema-list">
        <li class="schema-item">title: string</li>
        <li class="schema-item">priority: low | high</li>
        <li class="schema-item">additionalProperties: false</li>
      </ul>
    </section>

    <section class="panel">
      <h2 class="section-title">Parsed object</h2>
      <dl v-if="visibleObject" class="object-grid">
        <dt class="object-key">title</dt>
        <dd class="object-value">{{ visibleObject.title ?? '...' }}</dd>
        <dt class="object-key">priority</dt>
        <dd class="object-value">{{ visibleObject.priority ?? '...' }}</dd>
      </dl>
      <p v-else class="empty">No object yet.</p>
    </section>

    <section class="panel">
      <h2 class="section-title">Raw JSON stream</h2>
      <pre class="raw-output">{{ text || status }}</pre>
    </section>

    <section class="panel">
      <h2 class="section-title">Inspect</h2>
      <p>{{ inspection.summary }}</p>
      <div class="actions">
        <button class="button" :disabled="!inspection.curl" type="button" @click="copyCurl">
          {{ copied }}
        </button>
        <button class="button" type="button" @click="clearTrace">Clear trace</button>
      </div>
      <h3 class="section-title">Timeline JSON</h3>
      <pre class="raw-output">{{ inspectionJson }}</pre>
      <h3 class="section-title">Provider trace</h3>
      <pre class="raw-output">{{ formatText(inspection.providerTrace) }}</pre>
      <h3 class="section-title">Request / response</h3>
      <pre class="raw-output">{{ formatText(inspection.request) }}</pre>
      <pre class="raw-output">{{ formatText(inspection.response) }}</pre>
    </section>
  </main>
</template>

<style scoped>
.object-demo {
  max-width: 760px;
  margin: 32px auto;
  font-family: system-ui, sans-serif;
}
.header {
  display: flex;
  align-items: baseline;
  justify-content: space-between;
  gap: 16px;
}
.title {
  margin: 0;
  font-size: 18px;
}
.provider-badge {
  margin: 0;
  font-size: 12px;
  color: #334155;
}
.field {
  display: block;
  margin: 16px 0 8px;
}
.textarea {
  width: 100%;
  padding: 8px;
  font: inherit;
}
.actions {
  display: flex;
  gap: 8px;
  margin: 12px 0;
}
.button {
  padding: 8px 16px;
}
.panel {
  margin-top: 16px;
  padding: 12px;
  border: 1px solid #e5e7eb;
  border-radius: 8px;
}
.section-title {
  margin: 0 0 8px;
  font-size: 14px;
}
.schema-list {
  margin: 0;
  padding-left: 20px;
}
.schema-item {
  margin: 4px 0;
}
.object-grid {
  display: grid;
  grid-template-columns: 96px 1fr;
  gap: 8px;
  margin: 0;
}
.object-key {
  color: #475569;
}
.object-value {
  margin: 0;
}
.raw-output {
  min-height: 64px;
  margin: 0;
  padding: 10px;
  overflow: auto;
  background: #f8fafc;
  border-radius: 6px;
  white-space: pre-wrap;
}
.empty {
  margin: 0;
  color: #64748b;
}
.error {
  color: #b00020;
}
</style>
